### ISSUE TITLE
Can't redirect into Landing Page 

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#10]
When attempting to redirect to the Landing Page, an error is encountered where the redirection fails.

Steps to Reproduce:

1. Access the system or platform.
2.  Perform an action that triggers a redirect to the Landing Page.
3. Observe that instead of being redirected to the Landing Page, users encounter an error message or are not redirected at all.

Expected Behavior:
Upon performing the action that necessitates a redirect, users should be seamlessly directed to the Landing Page without encountering any errors.

Observed Behavior:
Instead of being redirected to the Landing Page, user is still seeing available cars without redirection.

**Comment by AashutoshDL** [comment]
![Screenshot 2024-04-20 172830](https://github.com/AashutoshDL/VROOM/assets/165886572/91c86978-c37c-4043-bc14-e03845e71fb9)
it seems that there is a bit of routing error in the code 
![image](https://github.com/AashutoshDL/VROOM/assets/165886572/2aac1a41-be54-4fa8-a6ba-6bd232c89058)
I have fixed the routing 
![image](https://github.com/AashutoshDL/VROOM/assets/165886572/bfd2cb68-fc70-4d7e-a8a4-9340dc55e335)
 Now it leads to the landing page
![image](https://github.com/AashutoshDL/VROOM/assets/165886572/45058b7f-3998-401e-b0f1-5dc5132aab77)

**Comment by riyadijju** [comment]
Looks good to me. Good work!
