### ISSUE TITLE
Documentation Improvement

### ISSUE THREAD

**Issue by AashutoshDL** [AashutoshDL/VROOM#11]
Lack of Clearance in documentation

Expected:
To have proper documentation and comments on the code

Observed:
Have comments but lack of clarity on the documentations

**Comment by Jengrg01** [comment]
Proper documentation created on read me and on codes
![image](https://github.com/AashutoshDL/VROOM/assets/119434270/6a34b363-8e14-4df6-bfe3-613ef53d2d11)
