### ISSUE TITLE
Improve User Experience on Car Selection Page

### ISSUE THREAD

**Issue by riyanashrestha3834** [AashutoshDL/VROOM#12]
It is essential to continually enhance the user experience to attract and retain customers. One area that requires attention is the user interface and functionality of the car selection page on our website. Currently, users may encounter difficulties in navigating through available car options or understanding rental terms and conditions, leading to potential frustration and reduced conversion rates.

Proposed Solution:

Implement intuitive filters and sorting options to help users easily find cars that meet their specific requirements, such as vehicle type, transmission, fuel type, and seating capacity.
Enhance the presentation of car listings with high-quality images, detailed descriptions, and key features highlighted prominently to provide users with comprehensive information.

Expected Outcome:
By improving the user experience on the car selection page, we aim to enhance user satisfaction, increase conversion rates, and ultimately drive growth for Vroom car rental services.

**Comment by Jengrg01** [comment]
Working on the UI/UX through frontend for filtering and visually appealing page which would be easy to navigate.  Please check the new updated website for further issues.
