### ISSUE TITLE
Register Button not Responsive in different frames.

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#23]
Bug Description
Register Button Not Responsive

Description: When accessing the registration page on devices with small screens, such as mobile phones or tablets, the "Register" button is not responsive. Instead of adapting to the smaller screen size, the button remains fixed in size and crops off, making it inaccessible to users.

Steps to Reproduce:

Access the registration page using a device with a small screen, such as a mobile phone or tablet.

Observe the layout of the registration form.

Attempt to locate and click on the "Register" button.

Expected Behavior: The "Register" button should dynamically adjust its size or layout to fit the smaller screen, ensuring it remains fully visible and clickable to users.

Actual Behavior: The "Register" button maintains its original size and position, causing it to crop off and become unresponsive on smaller screens.

Impact: This issue prevents users with small-screen devices from completing the registration process, potentially leading to a loss of new user sign-ups and impacting user experience negatively.

[wireframe]
(https://www.figma.com/file/lDyVHMFNc6qn9FEc49kVPu/Figma-Project?type=design&node-id=429-339&mode=design&t=FmP3FBqHS0LgYNl3-11)

**Comment by Jengrg01** [comment]
the button has been fixed.
