### ISSUE TITLE
Previous Date Booking Available in Car rentals

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#24]
Title: Users Can Book Cars for Past Dates

Description: Currently, users have the ability to book cars for past dates on the Vroom Car Rental platform, which is unintended behavior. This bug allows users to select and confirm bookings for dates that have already passed, leading to potential confusion, scheduling conflicts, and operational challenges for the rental service.

Steps to Reproduce:

Navigate to the Vroom Car Rental website and log in with valid credentials.

Go to the booking section or search for available cars.

Select a car rental option and proceed to the booking details page.

Choose a pickup date that is in the past (e.g., yesterday or any date prior to the current date).

Complete the booking process by confirming the reservation.

Note that the system accepts the booking for the past date without any error or warning message. This needs to be fixed asap.

Steps to Reduce:

Input Validation: Implement input validation mechanisms to ensure that users cannot select past dates for car bookings. This can include client-side validation using JavaScript to restrict date selection in the booking form.

Date Picker Configuration: Configure the date picker component to disable past dates, preventing users from selecting them during the booking process. This can be achieved by setting a minimum selectable date equal to the current date.

Backend Validation: Implement server-side validation checks to verify the selected booking dates against the current date. If a past date is detected, the system should reject the booking request and return an appropriate error response to the user interface.

Error Handling: Enhance error handling mechanisms to provide clear and informative error messages to users when attempting to book cars for past dates. This will help users understand why their booking requests are being rejected and how to proceed correctly.

**Comment by Dolma1** [comment]
![Screenshot 2024-05-11 160931](https://github.com/AashutoshDL/VROOM/assets/119917405/63065c7e-11fd-4ece-9894-009562050c4e)
minDate={new Date()} this line of code disables the past date  while booking

**Comment by Dolma1** [comment]
![image](https://github.com/AashutoshDL/VROOM/assets/119917405/b6707008-6b76-4c14-a950-4a02b2b865c6)
Paste date has been disable for both pick up and drop off
