### ISSUE TITLE
Central Alignment after booking

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#26]
Issue Description:

The booking confirmation message or modal is not centrally aligned on the user interface after completing a booking transaction, resulting in a lack of visual consistency and potential user confusion.

Description: Upon completing a booking transaction on the Vroom Car Rentals platform, users should receive a confirmation message or modal indicating the successful booking. However, it has been observed that this confirmation message or modal is not centrally aligned on the user interface. Instead, it appears misaligned or off-center, which can lead to a disjointed user experience and make it difficult for users to quickly locate and process the confirmation information.

Steps to Reproduce:

Navigate to the Vroom Car Rentals website.

Select a vehicle and proceed to the booking process.

Complete the booking transaction by providing the necessary details and confirming the reservation.

Observe the placement and alignment of the booking confirmation message or modal on the user interface.

Expected Behavior:

The booking confirmation message or modal should be centrally aligned on the user interface, ensuring visual consistency and easy identification by users.

The confirmation message or modal should be prominently displayed, with clear and concise information about the booked reservation.

Actual Behavior:

The booking confirmation message or modal appears misaligned or off-center on the user interface, deviating from the expected central alignment.

Users may struggle to locate and process the confirmation information due to its inconsistent placement and alignment.

Impact:

User Confusion: Misaligned or off-center confirmation messages can confuse users, leading to uncertainty about the status of their booking transaction.

Decreased Usability: Poorly aligned confirmation messages hinder the usability of the platform, as users may struggle to locate and interact with important information.

Negative Perception: Users may perceive the platform as unprofessional or poorly designed if visual inconsistencies persist across the user interface.

[Wireframe](https://www.figma.com/file/lDyVHMFNc6qn9FEc49kVPu/Figma-Project?type=design&node-id=656-23&mode=design&t=jxPaUi225WLaGI0l-11)

**Comment by pradhansumitXD** [comment]
Alignment issue with booking confirmation resolved.
