### ISSUE TITLE
Can't add my phone number. Default persists

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#6]
In the Signup page, user can't add their number. the default number stays there even if the changes are done. LMK if it's fixed!

**Comment by AashutoshDL** [comment]
it seems that i have set the default value as a dummy value 
![image](https://github.com/AashutoshDL/VROOM/assets/165886572/e226bde0-3ac4-44de-a6c3-28180901c609)
![image](https://github.com/AashutoshDL/VROOM/assets/165886572/2c2a3752-109f-434f-ac65-d7f034330885)
i have fixed it with a placeholder text now it works perfectly
