### ISSUE TITLE
http localhost url not working for admin dashboard

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#7]
Bug Description:
Users are unable to access the admin dashboard via the HTTP localhost URL.

Steps to Reproduce:
Open a web browser.

1. Enter the HTTP localhost URL for the admin dashboard (e.g., http://localhost/admin).
2. Attempt to access the admin dashboard.
3. Observe that the page fails to load or an error message is displayed.

Expected Behavior:
Users should be able to access the admin dashboard successfully using the HTTP localhost URL.

Observed Behavior:
Instead of accessing the admin dashboard, users encounter an error or the page fails to load.

Additional Information:

The issue seems to be specific to accessing the admin dashboard via the localhost URL.
Accessing other parts of the application via localhost works correctly.
There have been no recent changes to the admin dashboard or its configuration.

**Comment by AashutoshDL** [comment]
![image](https://github.com/AashutoshDL/VROOM/assets/165886572/89722aa9-98a6-43a6-a413-069cd7ebecd8)
there is no error in the code however you need to start the server also

![image](https://github.com/AashutoshDL/VROOM/assets/165886572/621ebdcd-e1e6-413d-bd39-12da19d25ead)

it leads to admin page perfectly now
