### ISSUE TITLE
Admin Panel button size reduce

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#8]
Admin dashboard, the buttons for managing new rentals and creation should be reduced according to the lofi designs.
<img width="479" alt="Screenshot 2024-04-20 at 3 35 08 PM" src="https://github.com/AashutoshDL/VROOM/assets/119119805/7d6820bf-83f5-4d7a-9ee8-ad05c02763ff">

**Comment by riyadijju** [comment]
Admin Panel [wireframe link](https://www.figma.com/file/lDyVHMFNc6qn9FEc49kVPu/Figma-Project?type=design&node-id=348-11&mode=design&t=owboMR09oaRNDjVX-4)

**Comment by pradhansumitXD** [comment]
Working on it will be fixed in an Hour
