### ISSUE TITLE
Background of Car in booking page white or default?

### ISSUE THREAD

**Issue by riyadijju** [AashutoshDL/VROOM#9]
<img width="765" alt="image" src="https://github.com/AashutoshDL/VROOM/assets/119119805/d056b785-4ca4-4a59-bfc3-f291476caf6b">

**Comment by riyadijju** [comment]
I think the bg for cars pov should have something since the theme is white already. LMK

**Comment by pradhansumitXD** [comment]
Ok I will change the background
